#!/usr/bin/env bash

mkdir $HOME/.config/kitty

echo "
background_opacity 0.90

font_family      \"Liberation Mono\"
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14

# Added by Gogh
include colors.conf
" > $HOME/.config/kitty/kitty.conf


echo "
# Color theme: Argonaut
# Auto-generated by Gogh (https://Gogh-Co.github.io/Gogh/)

color0  #232323
color1  #FF000F
color2  #8CE10B
color3  #FFB900
color4  #008DF8
color5  #6D43A6
color6  #00D8EB
color7  #FFFFFF
color8  #444444
color9  #FF2740
color10 #ABE15B
color11 #FFD242
color12 #0092FF
color13 #9A5FEB
color14 #67FFF0
color15 #FFFFFF
background #0E1019
foreground #FFFAF4
cursor #FFFAF4
" > $HOME/.config/kitty/colors.conf
