#!/usr/bin/env bash

mkdir $HOME/.config/kitty

echo "
background_opacity 0.90
font_size 12

# Added by Gogh
include colors.conf



# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
" > $HOME/.config/kitty/kitty.conf


echo "
# Color theme: Ibm 3270 (High Contrast)
# Auto-generated by Gogh (https://Gogh-Co.github.io/Gogh/)

color0  #000000
color1  #FF0000
color2  #00FF00
color3  #FFFF00
color4  #00BFFF
color5  #FFC0CB
color6  #40E0D0
color7  #BEBEBE
color8  #414141
color9  #FFA500
color10 #98FB98
color11 #FFFF00
color12 #0000CD
color13 #A020F0
color14 #AEEEEE
color15 #FFFFFF
background #000000
foreground #FDFDFD
cursor #FDFDFD
" > $HOME/.config/kitty/colors.conf
