#!/usr/bin/env bash

mkdir $HOME/.config/kitty

echo "
background_opacity 0.90

font_family      \"Liberation Mono\"
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14

# Added by Gogh
include colors.conf
" > $HOME/.config/kitty/kitty.conf


echo "
# Color theme: Atom
# Auto-generated by Gogh (https://Gogh-Co.github.io/Gogh/)

color0  #000000
color1  #FD5FF1
color2  #87C38A
color3  #FFD7B1
color4  #85BEFD
color5  #B9B6FC
color6  #85BEFD
color7  #E0E0E0
color8  #000000
color9  #FD5FF1
color10 #94FA36
color11 #F5FFA8
color12 #96CBFE
color13 #B9B6FC
color14 #85BEFD
color15 #E0E0E0
background #161719
foreground #C5C8C6
cursor #C5C8C6
" > $HOME/.config/kitty/colors.conf
